  name: Playwright Python CI
  on:
    workflow_dispatch:
  jobs:
    build:
      runs-on: ubuntu-latest

      services:
        xvfb:
          image: selenium/standalone-chrome:latest
          ports:
            - 4444:4444
          options: >-
            --shm-size 2g
            --health-cmd "curl -sS http://localhost:4444/wd/hub/status || exit 1"
            --health-timeout 5s

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
              python-version: '3.10'

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r wymagania.txt
              playwright install --with deps

        - name: Create screenshot directory
          run: |
            mkdir screenshot
        - name: Run tests
          run: |
            pytest
        - name: Upload screenshot
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: screenshot
            path: screenshot
